behaviors:
  HoopAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 100240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      vis_encode_type: simple
      normalize: False
      hidden_units: 128
      num_layers: 2
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          vis_encode_type: simple
          normalize: False
          hidden_units: 128
          num_layers: 2
          memory: null
          goal_conditioning_type: hyper
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 2000
    threaded: False
   
